language: php
php:
  - 5.3
  - 5.5
  - 5.4
  - hhvm
install:
  - composer update --prefer-source
before_script: echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - bash runtests.sh
